name: build
on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: ""
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - name: build apk if merge completed
        run: |
          if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            flutter build apk --split-per-abi
          fi
      - name: store artifacts only merged
        run: |
          if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            # Store built artifacts here (adapt path)
            mv build/app/outputs/apk/* build/artifacts/
          fi
      - name: extracting version
        run: |
          if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            echo "VERSION=$(cat pubspec.yaml | grep version: | cut -d ' ' -f 2)" >> $GITHUB_ENV
          fi
      - name: upload artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/artifacts/*
          token: ${{ secrets.token }}
          tag: ${{ env.VERSION }}
          
        

        
        
        
        
      